package it.quasar_x7.swing.vista;

import it.quasar_x7.controllo.FinestraGestioneUtentiController;
import it.quasar_x7.modello.DatiUtente;
import it.quasar_x7.swing.Finestra;



/**
 * Classe che gestisce la finestra della gestione degli utenti.
 * 
 * @author Ing. Domenico della Peruta
 * @version 1.1.0 ultima modifica 02/11/18
 */
public class FinestraGestioneUtenti extends javax.swing.JFrame {
    
    private DatiUtente dati=null;
    public int uscita = javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
    private final FinestraGestioneUtentiController gestore;
    /**
     * Creates new form FinestraGestione
     * @param dati
     * @param chiusuraProgramma
     */
    public FinestraGestioneUtenti(DatiUtente dati,boolean chiusuraProgramma) {
        if(chiusuraProgramma)
            uscita = javax.swing.WindowConstants.EXIT_ON_CLOSE;
        initComponents();
        this.dati =dati;
        gestore = new FinestraGestioneUtentiController(this,dati);
        gestore.creaLista();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pannello = new javax.swing.JPanel();
        pulsanteSalva = new javax.swing.JButton();
        pulsanteElimina = new javax.swing.JButton();
        pulsanteAggiungi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(uscita);
        setBackground(new java.awt.Color(51, 51, 51));

        sfondo.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBorder(null);

        pannello.setBackground(new java.awt.Color(204, 204, 204));
        pannello.setMinimumSize(new java.awt.Dimension(490, 550));
        pannello.setPreferredSize(new java.awt.Dimension(490, 550));

        javax.swing.GroupLayout pannelloLayout = new javax.swing.GroupLayout(pannello);
        pannello.setLayout(pannelloLayout);
        pannelloLayout.setHorizontalGroup(
            pannelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        pannelloLayout.setVerticalGroup(
            pannelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pannello);

        pulsanteSalva.setText("Salva");
        pulsanteSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteSalvaActionPerformed(evt);
            }
        });

        pulsanteElimina.setText("Elimina");
        pulsanteElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEliminaActionPerformed(evt);
            }
        });

        pulsanteAggiungi.setText("Aggiungi");
        pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestione Accessi");

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulsanteSalva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pulsanteElimina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pulsanteAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(pulsanteAggiungi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsanteElimina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pulsanteSalva))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pulsanteSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteSalvaActionPerformed
        gestore.salva(evt);
    }//GEN-LAST:event_pulsanteSalvaActionPerformed

    private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteAggiungiActionPerformed
        if(evt.getSource() instanceof javax.swing.JButton){
            Finestra.creaFinestra(new FinestraCreaUtente(dati,uscita));
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_pulsanteAggiungiActionPerformed

    private void pulsanteEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteEliminaActionPerformed
        gestore.elimina(evt);
    }//GEN-LAST:event_pulsanteEliminaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pannello;
    public javax.swing.JButton pulsanteAggiungi;
    public javax.swing.JButton pulsanteElimina;
    public javax.swing.JButton pulsanteSalva;
    private javax.swing.JPanel sfondo;
    // End of variables declaration//GEN-END:variables
}
